# Generated by Django 2.1.3 on 2018-11-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lytics_tables', '0002_auto_20181127_0134'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channels',
            table='channels',
        ),
    ]
